## Importing the libraries

In [0]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## Importing the dataset

In [0]:
dataset=pd.read_csv('Data.csv')
X=dataset.iloc[:,:-1].values
Y=dataset.iloc[:,-1].values

## Splitting the dataset into the Training set and Test set

In [0]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.25,random_state=0)

## Feature Scaling

In [0]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

# **Logistic Regression**

## Training the model 

In [5]:
from sklearn.linear_model import LogisticRegression
classifier_logis=LogisticRegression()
classifier_logis.fit(X_train,Y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

## Making the Confusion Matrix

In [6]:
from sklearn.metrics import confusion_matrix, accuracy_score
Y_pred_logis = classifier_logis.predict(X_test)
cm_logis = confusion_matrix(Y_test, Y_pred_logis)
print(cm_logis)
accuracy_score(Y_test, Y_pred_logis)

[[103   4]
 [  5  59]]


0.9473684210526315

# **K-Nearest Neighbors (K-NN)**

## Training the model

In [7]:
from sklearn.neighbors import KNeighborsClassifier
classifier_knn=KNeighborsClassifier(n_neighbors=5,metric='minkowski',p=2)
classifier_knn.fit(X_train,Y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

## Making the Confusion Matrix

In [8]:
from sklearn.metrics import confusion_matrix, accuracy_score
Y_pred_knn = classifier_knn.predict(X_test)
cm_knn = confusion_matrix(Y_test, Y_pred_knn)
print(cm_knn)
accuracy_score(Y_test, Y_pred_knn)

[[103   4]
 [  5  59]]


0.9473684210526315

# **Support Vector Machine (SVM)**

## Training the model

In [9]:
from sklearn.svm import SVC
classifier_svm = SVC(kernel = 'linear', random_state = 0)
classifier_svm.fit(X_train, Y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=0, shrinking=True, tol=0.001,
    verbose=False)

## Making the Confusion Matrix

In [10]:
from sklearn.metrics import confusion_matrix, accuracy_score
Y_pred_svm = classifier_svm.predict(X_test)
cm_svm = confusion_matrix(Y_test, Y_pred_svm)
print(cm_svm)
accuracy_score(Y_test, Y_pred_svm)

[[102   5]
 [  5  59]]


0.9415204678362573

# **Kernel SVM**

## Training the model

In [11]:
from sklearn.svm import SVC
classifier_ker= SVC(kernel = 'rbf', random_state = 0)
classifier_ker.fit(X_train, Y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=0, shrinking=True, tol=0.001,
    verbose=False)

## Making the Confusion Matrix

In [12]:
from sklearn.metrics import confusion_matrix, accuracy_score
Y_pred_ker = classifier_ker.predict(X_test)
cm_ker = confusion_matrix(Y_test, Y_pred_ker)
print(cm_ker)
accuracy_score(Y_test, Y_pred_ker)

[[102   5]
 [  3  61]]


0.9532163742690059

# **Naive Bayes**

## Training the model

In [13]:
from sklearn.naive_bayes import GaussianNB
classifier_nab=GaussianNB()
classifier_nab.fit(X_train,Y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

## Making the Confusion matrix

In [14]:
from sklearn.metrics import confusion_matrix, accuracy_score
Y_pred_nab = classifier_nab.predict(X_test)
cm_nab = confusion_matrix(Y_test, Y_pred_nab)
print(cm_nab)
accuracy_score(Y_test, Y_pred_nab)

[[99  8]
 [ 2 62]]


0.9415204678362573

# **Decision Tree Classification**

## Training the model

In [15]:
from sklearn.tree import DecisionTreeClassifier
classifier_tree=DecisionTreeClassifier(criterion='entropy',random_state=0)
classifier_tree.fit(X_train,Y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='entropy',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=0, splitter='best')

## Making the Confusion Matrix

In [16]:
from sklearn.metrics import confusion_matrix, accuracy_score
Y_pred_tree = classifier_tree.predict(X_test)
cm_tree = confusion_matrix(Y_test, Y_pred_tree)
print(cm_tree)
accuracy_score(Y_test, Y_pred_tree)

[[103   4]
 [  3  61]]


0.9590643274853801

# **Random Forest Classification**

## Training the model

In [17]:
from sklearn.ensemble import RandomForestClassifier
classifier_for=RandomForestClassifier(n_estimators=10,criterion='gini',random_state=0)
classifier_for.fit(X_train,Y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

## Making the Confusion Matrix

In [18]:
from sklearn.metrics import confusion_matrix, accuracy_score
Y_pred_for = classifier_for.predict(X_test)
cm_for = confusion_matrix(Y_test, Y_pred_for)
print(cm_for)
accuracy_score(Y_test, Y_pred_for)

[[102   5]
 [  4  60]]


0.9473684210526315